# Exercise 1
Implement KNN by hand for just 2 dimensions with normalization.  
  
This is easy because:
- funct: You normalize your data in another table
- funct: You code a simple euclid distance function
- funct: You take a point and calculate the distance to all points
- funct: You take the list from above and sort it
- funct: You aggregate by target variable
- funct: you take the max to determine the targe class
you are finished!  
  
Note: This is the only chance to implement a machine learning algorithm by hand and hence learn something from the ground up!  

In [1]:
import math
import random
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
data = iris.data
labels = iris.target

In [3]:
indices = list(range(len(data)))
random.shuffle(indices)

n_training_samples = 12
learn_data = data[indices[:-n_training_samples]]
learn_labels = labels[indices[:-n_training_samples]]

test_data = [4.8,2.5,5.3,2.4]

In [4]:
def distance(instance1, instance2):
    distance = 0.0
    for i in range(len(instance1) - 1):
        distance += (instance1[i] - instance2[i]) ** 2
    return math.sqrt(distance)

In [5]:
def get_neighbors(training_set, 
                  labels, 
                  test_instance, 
                  k, 
                  distance=distance):
    """
    get_neighors calculates a list of the k nearest neighbors
    of an instance 'test_instance'.
    The list neighbors contains 3-tuples with  
    (index, dist, label)
    where 
    index    is the index from the training_set, 
    dist     is the distance between the test_instance and the 
             instance training_set[index]
    distance is a reference to a function used to calculate the 
             distances
    """
    distances = []
    for index in range(len(training_set)):
        dist = distance(test_instance, training_set[index])
        distances.append((training_set[index], dist, labels[index]))
    distances.sort(key=lambda x: x[1])
    neighbors = distances[:k]
    return neighbors

In [6]:
def incr_dict(the_dict, key):
    the_dict[key] = the_dict.get(key, 0) + 1

In [7]:
def vote(neighbors):
    classes = dict()
    for neighbor in neighbors:
        incr_dict(classes, neighbor[2])
        
    return(max(classes, key=classes.get))

In [8]:
neighbors = get_neighbors(learn_data, 
                          learn_labels, 
                          test_data, 
                          3, 
                          distance=distance)
neighbors

[(array([4.9, 2.5, 4.5, 1.7]), 0.8062257748298548, 2),
 (array([5.6, 2.8, 4.9, 2. ]), 0.9433981132056599, 2),
 (array([5.7, 2.5, 5. , 2. ]), 0.948683298050514, 2)]

In [9]:
voted = vote(neighbors)
print("result of vote: ", voted, 
      ", data: ", test_data,
      ", label: ", iris.target_names[voted])

result of vote:  2 , data:  [4.8, 2.5, 5.3, 2.4] , label:  virginica


The flower has been classified as **virginica**

# Exercise 2
In the logistic regression example, I gave you a new iris data:  
4.8,2.5,5.3,2.4  
Please classify this flower using KNN (with all libs available as you like)

In [10]:
import numpy as np

In [11]:
def distance(instance1, instance2):
    instance1 = np.array(instance1) 
    instance2 = np.array(instance2)
    
    return np.linalg.norm(instance1 - instance2)

In [12]:
from collections import Counter
def vote(neighbors):
    class_counter = Counter()
    for neighbor in neighbors:
        class_counter[neighbor[2]] += 1
    return class_counter.most_common(1)[0][0]

In [13]:
neighbors = get_neighbors(learn_data, 
                          learn_labels, 
                          test_data, 
                          3, 
                          distance=distance)
neighbors

[(array([5.6, 2.8, 4.9, 2. ]), 1.0246950765959595, 2),
 (array([5.7, 2.5, 5. , 2. ]), 1.0295630140987002, 2),
 (array([5.8, 2.8, 5.1, 2.4]), 1.0630145812734648, 2)]

In [14]:
voted = vote(neighbors)
print("result of vote: ", voted, 
      ", data: ", test_data,
      ", label: ", iris.target_names[voted])

result of vote:  2 , data:  [4.8, 2.5, 5.3, 2.4] , label:  virginica


The flower has been classified as **virginica**