# 1. Import numpy as np and see the version

In [72]:
import numpy as np
import sys as sys

# 2. How to create a 1D array?

In [2]:
one_dim_array = np.arange(10)

In [3]:
one_dim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [4]:
bool_array = np.full((3, 3), True, dtype=bool)

In [5]:
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
bool_array = np.ones((3,3), dtype=bool)

In [7]:
bool_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4. How to extract items that satisfy a given condition from 1D array?

In [8]:
extract_arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
extract_arr[extract_arr % 2 == 1]

array([1, 3, 5, 7, 9])

# 5. How to replace items that satisfy a condition with another value in numpy array?

In [10]:
odd_replace_arr = np.arange(10)

In [11]:
odd_replace_arr[odd_replace_arr % 2 == 1] = -1

In [12]:
odd_replace_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?

In [13]:
replace_copy_arr = np.arange(10)

In [14]:
replace_copy_arr_copy = np.where(replace_copy_arr % 2 == 1, -1, replace_copy_arr)

In [15]:
replace_copy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
replace_copy_arr_copy

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 7. How to reshape an array?

In [17]:
reshape_arr = np.arange(10)

In [18]:
reshape_arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. How to stack two arrays vertically?

In [19]:
stack_arr_a = np.arange(10).reshape(2, -1)
stack_arr_b = np.repeat(1,10).reshape(2, -1)

In [20]:
np.concatenate([stack_arr_a,stack_arr_b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.vstack([stack_arr_a,stack_arr_b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.r_[stack_arr_a,stack_arr_b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9. How to stack two arrays horizontally?

In [23]:
stack2_arr_a = np.arange(10).reshape(2, -1)
stack2_arr_b = np.repeat(1,10).reshape(2, -1)

In [24]:
np.concatenate([stack2_arr_a,stack2_arr_b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
np.hstack([stack2_arr_a, stack2_arr_b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
np.c_[stack2_arr_a,stack2_arr_b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10. How to generate custom sequences in numpy without hardcoding?

In [27]:
custom_generate_arr = np.array([1,2,3])

In [28]:
custom_generate_arr

array([1, 2, 3])

In [29]:
np.r_[np.repeat(custom_generate_arr, 3), np.tile(custom_generate_arr, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?

In [30]:
common_arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
common_arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

In [31]:
np.intersect1d(common_arr_a, common_arr_b)

array([2, 4])

# 12. How to remove from one array those items that exist in another?

In [32]:
remove_common_arr_a = np.array([1,2,3,4,5])
remove_common_arr_b = np.array([5,6,7,8,9])

In [33]:
np.setdiff1d(remove_common_arr_a, remove_common_arr_b)

array([1, 2, 3, 4])

# 13. How to get the positions where elements of two arrays match?

In [34]:
match_arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
match_arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

In [35]:
np.where(match_arr_a == match_arr_b)

(array([1, 3, 5, 7], dtype=int64),)

# 14. How to extract all numbers between a given range from a numpy array?

In [36]:
between_arr = np.array([2, 6, 1, 9, 10, 3, 27])

In [37]:
between_arr[(between_arr >= 5) & (between_arr <= 10)]

array([ 6,  9, 10])

# 15. How to make a python function that handles scalars to work on numpy arrays?

In [38]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [39]:
max_arr_a = np.array([5, 7, 9, 8, 6, 4, 5])
max_arr_b = np.array([6, 3, 4, 8, 9, 7, 1])

In [40]:
pair_max = np.vectorize(maxx, otypes=[float])

In [41]:
pair_max(max_arr_a,max_arr_b)

array([6., 7., 9., 8., 9., 7., 5.])

# 16. How to swap two columns in a 2d numpy array?

In [42]:
swap_arr = np.arange(9).reshape(3,3)

In [43]:
swap_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
swap_arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17. How to swap two rows in a 2d numpy array?

In [45]:
swap2_arr = np.arange(9).reshape(3,3)

In [46]:
swap2_arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18. How to reverse the rows of a 2D array?

In [47]:
reverse_arr = np.arange(9).reshape(3,3)

In [48]:
reverse_arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19. How to reverse the columns of a 2D array?

In [49]:
reverse2_arr = np.arange(9).reshape(3,3)

In [50]:
reverse2_arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20. How to create a 2D array containing random floats between 5 and 10?

In [51]:
rand_arr = np.random.randint(low=5, high=10, size=(5,3))

In [52]:
print(rand_arr)

[[5 5 5]
 [9 5 5]
 [9 8 8]
 [5 7 7]
 [6 7 5]]


# 21. How to print only 3 decimal places in python numpy array?

In [53]:
decimal_places_arr = np.random.random((5,3))

In [54]:
decimal_places_arr

array([[0.59915685, 0.56376513, 0.53643931],
       [0.18121843, 0.01610983, 0.13510111],
       [0.3400914 , 0.08862105, 0.06845031],
       [0.84319229, 0.16041656, 0.03548784],
       [0.47162088, 0.66947735, 0.39202031]])

In [55]:
np.set_printoptions(precision=3)

In [56]:
decimal_places_arr

array([[0.599, 0.564, 0.536],
       [0.181, 0.016, 0.135],
       [0.34 , 0.089, 0.068],
       [0.843, 0.16 , 0.035],
       [0.472, 0.669, 0.392]])

# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [57]:
np.random.seed(100)
scientific_arr = np.random.random((3,3)) / 1e3

In [58]:
scientific_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [61]:
np.set_printoptions(suppress=True, precision=6)

In [62]:
scientific_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# 23. How to limit the number of items printed in output of numpy array?

In [63]:
limit_arr = np.arange(15)

In [64]:
np.set_printoptions(threshold=6)

In [65]:
limit_arr

array([ 0,  1,  2, ..., 12, 13, 14])

# 24. How to print the full numpy array without truncating

In [67]:
np.set_printoptions(threshold=6)
no_trunc_arr = np.arange(15)

In [68]:
no_trunc_arr

array([ 0,  1,  2, ..., 12, 13, 14])

In [73]:
np.set_printoptions(threshold=sys.maxsize)

In [74]:
no_trunc_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [75]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [76]:
iris[::3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.7', b'3.8', b'1.7', b'0.3', b'Iris-setosa'],
       [b'5.1', b'3.7', b'1.5', b'0.4', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'5.2', b'3.5', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'5.5', b'4.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.5', b'3.5', b'1.3', b'0.2', b'Iris-setosa'],
       [b'5.1', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.3', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'6.4', b'3.2', b'4.5',